### ISSUE TITLE
Comment source code and use descriptive variable names 

### ISSUE THREAD

**Issue by srguiwiz** [jurisv/nodejs.extdirect#21]
More descriptive variable names and comments in router.js would be very helpful.

I am working on a system architecture document, part of which describes middleware, which uses nodejs.extdirect.  Today I tried to correctly describe exception handling and method batching.

I have understood much of router.js a while ago.  But this second time "what does this code do" makes me recognize the need for descriptive variable names in router.js and comments describing intent of loops, conditionals, etc.  That will enable meaningful review of this package.

I think the original author should have a first go.

**Comment by jurisv** [comment]
Fixed via:
https://github.com/jurisv/nodejs.extdirect/commit/283ec487913b66547f5c7bf03447530321cae144
