### ISSUE TITLE
New metadata property support

### ISSUE THREAD

**Issue by nikolaybobrovskiy** [jurisv/nodejs.extdirect#27]
As stated in 5.1 what's new:
"Full metadata support

One of the frequently requested features for Direct subsystem was support for passing metadata with CRUD operations in a Proxy. Previously this was implemented only for Read operations using extraParams property on the Proxy; unfortunately that approach made it near impossible to support CUD operations as well.

Starting with Ext JS 5.1, any Direct method invocation can be supplied with metadata that will be passed to the server side separately from method arguments. This feature is immediately available with Direct proxy as well via the new metadata property that can be used instead of extraParams with full range of CRUD operations."

http://docs.sencha.com/extjs/5.1/5.1.0-apidocs/#!/api/Ext.data.proxy.Direct-cfg-metadata

**Comment by jurisv** [comment]
Feature added
