### ISSUE TITLE
nodejs constantly crashes on OSX (Yosemite)

### ISSUE THREAD

**Issue by Reggae13** [jurisv/nodejs.extdirect#32]
Whenever I try to start the demo-app, I get the following  error from node.js

/Library/Server/Node/mysql/direct/.DS_Store:1
(function (exports, require, module, __filename, __dirname) { 
                                                              
SyntaxError: Unexpected token ILLEGAL

When deleting the file .DS_Store in the /direct folder the app starts once but immediately crashes again when trying to execute a function.

**Comment by jurisv** [comment]
Upgrade is work in progress. Use the npmjs latest version instead.

**Comment by jurisv** [comment]
Because API discovery will pick up all files in /direct folder it found .DS_Store cache file and got confused. I will add check to exclude it in the next release.
